sudo: required

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - docker pull maven

script:
  - docker run -it --rm -v "$PWD":/code-tracking -w /code-tracking maven mvn clean install
